version: "3"
services:
  mountebank:
    container_name: mountebank
    image: jkris/mountebank:2.4.0
    volumes:
      - ./imposters:/imposters
    ports:
      - 2525:2525
      - 8090:8090
    command: --configfile /imposters/imposters.ejs --allowInjection